export const POWER_VOTING_VOTE = "POWER_VOTING_VOTE";
export const POWER_VOTING_FIP = "POWER_VOTING_FIP";
export const POWER_VOTING_ORCAL = "POWER_VOTING_ORCAL";
export const POWER_VOTING_POWER = "POWER_VOTING_POWER";

