FROM golang:alpine AS snapshot-builder

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64


# move to work dir：/build
WORKDIR /build


COPY power-snapshot/go.mod power-snapshot/go.sum ./
RUN go mod tidy

COPY power-snapshot/. .

RUN go build -o app .

FROM alpine:latest

WORKDIR /dist

COPY --from=snapshot-builder /build/app .
COPY --from=snapshot-builder /build/configuration.yaml  .
COPY --from=snapshot-builder /build/proof.ucan ./

# run
CMD ["/dist/app"]