FROM golang:alpine AS snapshot-builder

RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64


# move to work dir：/build
WORKDIR /build


COPY snapshot/go.mod snapshot/go.sum ./
RUN go mod tidy

COPY snapshot/. .

RUN go build -o app .

FROM alpine:latest

WORKDIR /dist

COPY --from=snapshot-builder /build/app .
COPY --from=snapshot-builder /build/configuration.yaml  .
COPY --from=snapshot-builder /build/proof.ucan ./

COPY --from=snapshot-builder /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Asia/Shanghai

# run
CMD ["/dist/app"]