server:
  # service startup port
  port: :10000

snapshot:
  rpc: localhost:8001

# drand api
drand:
  url:
    - "https://api.drand.secureweb3.com:6875"
    - "https://api.drand.sh/"
    - "https://api2.drand.sh/"
    - "https://api3.drand.sh/"
    - "https://drand.cloudflare.com/"
  chainHash: "52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971"

mysql:
  url: localhost:3306
  username: root
  password: root

network:
  - id: 314159
    name: FileCoin-Calibration
    rpc: http://203.160.91.77:27924/rpc/v1
    powerVotingAbi: power-voting.json
    oracleAbi: oracle.json
    powerVotingContract:
    oracleContract:

w3client:
  did: 
  privateKey: 
   # proof.ucan path
  proof: 