// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.5
// source: backend.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend_GetAllVoterAddresss_FullMethodName = "/rpc.Backend/GetAllVoterAddresss"
	Backend_GetVoterInfo_FullMethodName        = "/rpc.Backend/GetVoterInfo"
	Backend_GetGithubRepoInfo_FullMethodName   = "/rpc.Backend/GetGithubRepoInfo"
)

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	GetAllVoterAddresss(ctx context.Context, in *GetAllVoterAddressRequest, opts ...grpc.CallOption) (*GetAllVoterAddressResponse, error)
	GetVoterInfo(ctx context.Context, in *GetVoterInfoRequest, opts ...grpc.CallOption) (*GetVoterInfoResponse, error)
	GetGithubRepoInfo(ctx context.Context, in *GetGithubRepoInfoRequest, opts ...grpc.CallOption) (*GetGithubRepoInfoResponse, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) GetAllVoterAddresss(ctx context.Context, in *GetAllVoterAddressRequest, opts ...grpc.CallOption) (*GetAllVoterAddressResponse, error) {
	out := new(GetAllVoterAddressResponse)
	err := c.cc.Invoke(ctx, Backend_GetAllVoterAddresss_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetVoterInfo(ctx context.Context, in *GetVoterInfoRequest, opts ...grpc.CallOption) (*GetVoterInfoResponse, error) {
	out := new(GetVoterInfoResponse)
	err := c.cc.Invoke(ctx, Backend_GetVoterInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetGithubRepoInfo(ctx context.Context, in *GetGithubRepoInfoRequest, opts ...grpc.CallOption) (*GetGithubRepoInfoResponse, error) {
	out := new(GetGithubRepoInfoResponse)
	err := c.cc.Invoke(ctx, Backend_GetGithubRepoInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
// All implementations must embed UnimplementedBackendServer
// for forward compatibility
type BackendServer interface {
	GetAllVoterAddresss(context.Context, *GetAllVoterAddressRequest) (*GetAllVoterAddressResponse, error)
	GetVoterInfo(context.Context, *GetVoterInfoRequest) (*GetVoterInfoResponse, error)
	GetGithubRepoInfo(context.Context, *GetGithubRepoInfoRequest) (*GetGithubRepoInfoResponse, error)
	mustEmbedUnimplementedBackendServer()
}

// UnimplementedBackendServer must be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (UnimplementedBackendServer) GetAllVoterAddresss(context.Context, *GetAllVoterAddressRequest) (*GetAllVoterAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVoterAddresss not implemented")
}
func (UnimplementedBackendServer) GetVoterInfo(context.Context, *GetVoterInfoRequest) (*GetVoterInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoterInfo not implemented")
}
func (UnimplementedBackendServer) GetGithubRepoInfo(context.Context, *GetGithubRepoInfoRequest) (*GetGithubRepoInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGithubRepoInfo not implemented")
}
func (UnimplementedBackendServer) mustEmbedUnimplementedBackendServer() {}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_GetAllVoterAddresss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVoterAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetAllVoterAddresss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetAllVoterAddresss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetAllVoterAddresss(ctx, req.(*GetAllVoterAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetVoterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetVoterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetVoterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetVoterInfo(ctx, req.(*GetVoterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetGithubRepoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGithubRepoInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetGithubRepoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetGithubRepoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetGithubRepoInfo(ctx, req.(*GetGithubRepoInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllVoterAddresss",
			Handler:    _Backend_GetAllVoterAddresss_Handler,
		},
		{
			MethodName: "GetVoterInfo",
			Handler:    _Backend_GetVoterInfo_Handler,
		},
		{
			MethodName: "GetGithubRepoInfo",
			Handler:    _Backend_GetGithubRepoInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
