network:
  - id: 314159
    name: Calibration
    # RPC url
    rpc: http://203.160.91.77:27924/rpc/v1
    #  absolute path
    abiPath: oracle_abi.json
    # contract address
    contractAddress: 0x14696967B6987Ae34c9018ed8D3955064d88231F
    # wallet private key
    privateKey:
    # wallet address
    walletAddress:
    # gas limit
    gasLimit:

github:
  # github token
  githubToken:
  # graphql api
  graphql: https://api.github.com/graphql
