// SPDX-License-Identifier: MIT

pragma solidity ^0.8.19;

struct VoteResult {
    // proposal option id, generated by frontend when create the proposal
    uint256 optionId;
    //  vote result
    uint256 votes;
}

struct Proposal {
    // proposal cid
    string cid;
    // proposal type
    uint256 proposalType;
    // proposal creator
    address creator;
    // proposal expiration timestamp, second
    uint248 expTime;
    // chain id
    uint256 chainId;
    // vote list cid
    string voteListCid;
    // whether proposal is counted
    ProposalStatus status;
    // proposal vote result list
    VoteResult[] voteResults;
}


// constant
uint256 constant RESULT_MAX_LENGTH = 5;
uint256 constant MAX_ADDRESS = 200;

// proposal status enum
enum ProposalStatus {
    InProgress,
    Completed,
    Canceled
}