# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: backend-test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          cd ./backend
          go mod tidy   

      - name: Initialize MySQL database
        run: |
          echo $(docker ps -q --filter ancestor=mysql:latest)
          docker exec -i $(docker ps -q --filter ancestor=mysql:latest) mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS \`power-voting-filecoin\`;"

      - name: Copy config file to test dir
        run: |
          cd ./backend
          cp ./abi/* ./task/event
          cp ./abi/* ./task
          cp ./abi/* ./utils

      - name: Test
        run: |
          cd ./backend
          go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.BUILD_PATH }}/backend
            sudo sh build.sh