name: Frontend ESLint

on:
  pull_request:
    branches:
      - main
    paths:
      - power-voting/*
  push:
    branches:
      - main
    paths:
      - power-voting/*

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd power-voting
          npm install -d

      - name: Lint
        run: |
          cd power-voting
          npm run lint
