name: Frontend Test

on:
  pull_request:
    branches:
      - main
    paths:
      - power-voting/*
  push:
    branches:
      - main
    paths:
      - power-voting/*

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd power-voting
          npm install -d

      - name: Test
        run: |
          cd power-voting
          npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.BUILD_PATH }}/power-voting
            sudo sh build.sh